services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DBPASS:?database password not set}
      POSTGRES_USER: ${DBUSER:?database user not set}
      POSTGRES_DB: ${DBNAME:?database name not set}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DBUSER} -d ${DBNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
    environment:
      DBHOST: db
    ports:
      - 5000:5000
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
volumes:
 postgres-data:
